[package]
name = "tokio-mock"
version = "0.1.0"
authors = ["Émile Grégoire <emile@stepfunc.io>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["net", "sync", "io-util", "io-std", "time", "rt", "rt-multi-thread", "macros"] }
