[package]
name = "tokio-mock"
version = "0.2.0"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["net", "sync", "io-util", "io-std", "time", "rt", "rt-multi-thread", "macros"] }
